### ISSUE TITLE
Password on raw_dp

### ISSUE THREAD

**Issue by rahul-nt** [littleaich/deepglobe2018#2]
Why is there a password on raw_dp.zip?

I'm facing an error:
Cannot open file ./mean

Is the above error related to the files compressed in raw_dp.zip?

**Comment by shubhraaich** [comment]
Hi rahul-nt,

raw_dp files are not absolutely necessary (they are mostly some initial EDA files), except save_mean_std.py and homogenize_name_format.py. I have uploaded them in the repo now. Don't forget to change the paths inside them.
(1) save_mean_std.py (use this to save mean and std of the dataset, or you might even use the standard imagenet ones).
(2) homogenize_name_format.py (this file renames both image and mask with the exact same tags, which makes data loading a bit simpler, even though using the original tags is also straightforward).

**Comment by rahul-nt** [comment]
Hi Shubhra

Thanks a lot for the explanation, and for updating the repo. It worked. Very grateful.
